models:
  publisher:
    fields:
      name:
      authors:
        type: manytomany
        to: author

    auth_type: basic

  author:
    fields:
      name:

  book:
    fields:
      name:
      author:
        type: foreignkey
        to: author

methods:
  - path: say-hello/<string:arg1>
    resource: HelloResource
    file: hello.py
    swagger:
      get:
        summary: a summary

users: